apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app: web-app
    tier: backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8089
  selector:
    app: web-app
    tier: backend
  type: LoadBalancer
