apiVersion: v1
kind: Service
metadata:
  name: host
  labels:
    app: host
    tier: backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: host
    tier: backend
  type: LoadBalancer
